# Generated by Django 5.1.2 on 2024-10-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='poster',
            field=models.ImageField(blank=True, default='poster/2024/10/16/test.jpg', upload_to='poster/%Y/%m/%d/'),
        ),
    ]
