# Generated by Django 5.1.2 on 2024-10-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviesmodel_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='poster',
            field=models.ImageField(blank=True, default='poster/Out_Of_Poster.jpg', upload_to='poster/%Y/%m/%d/'),
        ),
    ]
