# Generated by Django 5.1.2 on 2024-10-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviesmodel_poster'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moviesmodel',
            index=models.Index(fields=['title'], name='movies_movi_title_830f2f_idx'),
        ),
    ]
