# Generated by Django 5.1.2 on 2024-10-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviesmodel_movies_movi_title_830f2f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moviesmodel',
            name='movies_movi_title_830f2f_idx',
        ),
    ]
