# Generated by Django 5.1.2 on 2024-10-19 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_moviesmodel_movies_movi_title_830f2f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmodel',
            name='rating',
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='rating',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
